<a href="https://colab.research.google.com/github/Fathima-Rinsha-k/LSTM/blob/main/Sample_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Steps to analyze the data**


1.   Load Dataset
2.   Find the missing values
3.   Handle missing values
      Remove the missing values
      Replace it by another values
4.   Retrieve the informations needed to apply
5.   Display the details

In [ ]:
import pandas as pd
df = pd.read_csv('/content/sample_data/missing_data_practice.csv')

In [ ]:
#to display the dataset
#df = pd.read_csv("file.csv",na_values=["null", "NaN", "None", ""])
df

   id   name  age  marks department  joining_date   salary
0   1   Riya   23   85.0         IT    2023-01-10  45000.0
1   2    Anu  NaN   90.0         HR    2023-02-15  50000.0
2   3    Tom   25    NaN    Finance    2023-03-20      NaN
3   4   John  abc   70.0         IT           NaN  48000.0
4   5    NaN   28    NaN  Marketing    2023-05-12  52000.0
5   6   Maya   30   88.0        NaN  invalid_date  60000.0
6   7   Arun        95.0         IT    2023-07-01      NaN
7   8   Neha   27   85.0         HR    2023-08-10  55000.0
8   9  Kiran  NaN  100.0    Finance    2023-09-05  65000.0
9  10  Divya   29    NaN  Marketing           NaN      NaN

In [ ]:
df.columns

Index(['id', 'name', 'age', 'marks', 'department', 'joining_date', 'salary'], dtype='object')

**Finding the missing values**

In [ ]:

df.isna()

      id   name    age  marks  department  joining_date  salary
0  False  False  False  False       False         False   False
1  False  False   True  False       False         False   False
2  False  False  False   True       False         False    True
3  False  False  False  False       False          True   False
4  False   True  False   True       False         False   False
5  False  False  False  False        True         False   False
6  False  False  False  False       False         False    True
7  False  False  False  False       False         False   False
8  False  False   True  False       False         False   False
9  False  False  False   True       False          True    True

In [ ]:
df.sum().isna()

TypeError: can only concatenate str (not "int") to str

In [ ]:
#checking for the datatypes
print(df.dtypes)

id                int64
name             object
age              object
marks           float64
department       object
joining_date     object
salary          float64
dtype: object

In [ ]:
#Displaying the columns having missing values using a loop
for col in df.columns:
    if pd.api.types.is_numeric_dtype(df[col]):
        continue
    else:
        print(f"Column '{col}' has non-numeric data.")

Column 'name' has non-numeric data.
Column 'age' has non-numeric data.
Column 'department' has non-numeric data.
Column 'joining_date' has non-numeric data.

In [ ]:

# Convert a specific column to numeric, setting invalid parsing to NaN
# Step 1: Define column types properly

numeric_cols = ['age', 'marks', 'salary']
date_cols = ['joining_date']

# Step 2: Convert numeric columns
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Step 3: Convert date columns
for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

In [ ]:
df.isna().sum()

id              0
name            1
age             4
marks           3
department      1
joining_date    3
salary          3
dtype: int64

**Handling the missing values**

In [ ]:
df.dropna()

   id  name   age  marks department joining_date   salary
0   1  Riya  23.0   85.0         IT   2023-01-10  45000.0
7   8  Neha  27.0   85.0         HR   2023-08-10  55000.0

In [ ]:
df.dropna(how ='all')

   id   name   age  marks department joining_date   salary
0   1   Riya  23.0   85.0         IT   2023-01-10  45000.0
1   2    Anu   NaN   90.0         HR   2023-02-15  50000.0
2   3    Tom  25.0    NaN    Finance   2023-03-20      NaN
3   4   John   NaN   70.0         IT          NaT  48000.0
4   5    NaN  28.0    NaN  Marketing   2023-05-12  52000.0
5   6   Maya  30.0   88.0        NaN          NaT  60000.0
6   7   Arun   NaN   95.0         IT   2023-07-01      NaN
7   8   Neha  27.0   85.0         HR   2023-08-10  55000.0
8   9  Kiran   NaN  100.0    Finance   2023-09-05  65000.0
9  10  Divya  29.0    NaN  Marketing          NaT      NaN

In [ ]:
df.dropna(thresh=6)

   id   name   age  marks department joining_date   salary
0   1   Riya  23.0   85.0         IT   2023-01-10  45000.0
1   2    Anu   NaN   90.0         HR   2023-02-15  50000.0
7   8   Neha  27.0   85.0         HR   2023-08-10  55000.0
8   9  Kiran   NaN  100.0    Finance   2023-09-05  65000.0

In [ ]:
df['name']=df['name'].fillna('n/a')
df['marks'] = df['marks'].fillna(0)
df['age']=df['age'].fillna(0)
df['department'] = df['department'].fillna('n/a')
df['joining_date'] = df['joining_date'].fillna('n/a')
df['salary']=df['salary'].fillna(0)

In [ ]:
df.isna().sum()

id              0
name            0
age             0
marks           0
department      0
joining_date    0
salary          0
dtype: int64

In [ ]:
df

   id   name   age  marks department         joining_date   salary
0   1   Riya  23.0   85.0         IT  2023-01-10 00:00:00  45000.0
1   2    Anu   0.0   90.0         HR  2023-02-15 00:00:00  50000.0
2   3    Tom  25.0    0.0    Finance  2023-03-20 00:00:00      0.0
3   4   John   0.0   70.0         IT                  n/a  48000.0
4   5    n/a  28.0    0.0  Marketing  2023-05-12 00:00:00  52000.0
5   6   Maya  30.0   88.0        n/a                  n/a  60000.0
6   7   Arun   0.0   95.0         IT  2023-07-01 00:00:00      0.0
7   8   Neha  27.0   85.0         HR  2023-08-10 00:00:00  55000.0
8   9  Kiran   0.0  100.0    Finance  2023-09-05 00:00:00  65000.0
9  10  Divya  29.0    0.0  Marketing                  n/a      0.0

**Retrieve the information to analyze**

In [ ]:
#Display all employees whose salary is greater than 50,000
df[df['salary']>50000]

   id   name   age  marks department         joining_date   salary
4   5    n/a  28.0    0.0  Marketing  2023-05-12 00:00:00  52000.0
5   6   Maya  30.0   88.0        n/a                  n/a  60000.0
7   8   Neha  27.0   85.0         HR  2023-08-10 00:00:00  55000.0
8   9  Kiran   0.0  100.0    Finance  2023-09-05 00:00:00  65000.0

In [ ]:
#Display employees who belong to the IT department AND have marks greater than 80
df[(df['department']=='IT') & (df['marks']>80)]

   id  name   age  marks department         joining_date   salary
0   1  Riya  23.0   85.0         IT  2023-01-10 00:00:00  45000.0
6   7  Arun   0.0   95.0         IT  2023-07-01 00:00:00      0.0

In [ ]:
#Display all rows where joining_date is missing.
df[df['joining_date']=='n/a']

   id   name   age  marks department joining_date   salary
3   4   John   0.0   70.0         IT          n/a  48000.0
5   6   Maya  30.0   88.0        n/a          n/a  60000.0
9  10  Divya  29.0    0.0  Marketing          n/a      0.0

In [ ]:
#Display rows where age is less than 18 OR greater than 60 OR is missing.
df[(df['age']<18)|
    (df['age']>60)|
    (df['age']==0)
  ]

   id   name  age  marks department         joining_date   salary
1   2    Anu  0.0   90.0         HR  2023-02-15 00:00:00  50000.0
3   4   John  0.0   70.0         IT                  n/a  48000.0
6   7   Arun  0.0   95.0         IT  2023-07-01 00:00:00      0.0
8   9  Kiran  0.0  100.0    Finance  2023-09-05 00:00:00  65000.0